language: java

jdk:
  - openjdk11

notifications:
  email: false

addons:
  sonarcloud:
    organization: "christiansantapaola" # the key of the org you chose at step #3
    token:
      secure: "KNYmUsbtNCbmR6ecbnywApLbgJ/ZxVU1ZzUFEjTzN/wRULeN4nDkjaGFogAEduh5rrnB12RPZRP5RKpM8JlxGPPAFr7XyqtBhhjqU5U+G4dIL0aGXTEuVFlhfOBgdqQVkoZXTPc29CZmdzb12Y4hvmdLvUVAAiIoy8few91qBjCsgAWd2iEHfmSReMFAY8D2avJDpwx/ez7XcSZtYgbbIvwfUutoGVrLZVaX2E0SKW9lPKfeMfqU7zPnlcodrxDsXMb+bkVqIa1Lk4WX/A+3cmkk2fvjlkcQ7544EYNuG9J2JxJgZdzlEjvaTeK6CiixQGcTTVMsbceu/Npf8Ce7b5PwGVMSBZqPoDrW/gr+JifyEmGocFvoryVswTO5BX2F61q94k+WVvEUv408NtG0uM7LFnBmE8QwcKw1JMARBoTxL5uZG2k4VANbc/EN4Pzk9fwqppaj+NinhgD3MUXBx11sk7F7aZuPCsbkhzbiPpOAtG4965BohEUH6r+PFbQ033iNxoEnYNCSUImUfOs+0WrRdgqRTZ0rKfQNau8RFhQFOAa4Z9J1LEsoQRasao3trFamOlXorG0FyBpyEdmXfIYuC+wNDUXIsHCb1+xSxwxmzlafn3cD+L+QBrFElXLsK8d8F1Ox2Oi8iEpj28fJNs7CE3pyIbavHqI9i26JzPY="

before_install:
  - >
    case "${TRAVIS_OS_NAME:-linux}" in
    linux)
      sudo apt-get update -qq
      sudo apt-get install -qq fakeroot
      curl https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2 -o gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2
      tar xfj gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2 -C platform_linux/
      rm gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2
      curl https://d3pxv6yz143wms.cloudfront.net/8.232.09.1/java-1.8.0-amazon-corretto-jdk_8.232.09-1_amd64.deb > java-1.8.0-amazon-corretto-jdk_8.232.09-1_amd64.deb
      sudo dpkg -i java-1.8.0-amazon-corretto-jdk_8.232.09-1_amd64.deb
      rm java-1.8.0-amazon-corretto-jdk_8.232.09-1_amd64.deb
      export OLD_JAVA_HOME=${JAVA_HOME}
      export JAVA_HOME="/usr/lib/jvm/java-1.8.0-amazon-corretto"
      ./platform_linux/build.sh --noninteractive
      ;;
    osx)
      brew update
      brew install ant p7zip
      curl https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-mac.tar.bz2 -o gcc-arm-none-eabi-7-2018-q2-update-mac.tar.bz2
      tar xfj gcc-arm-none-eabi-7-2018-q2-update-mac.tar.bz2 -C /Applications/
      rm gcc-arm-none-eabi-7-2018-q2-update-mac.tar.bz2
      curl https://d3pxv6yz143wms.cloudfront.net/8.232.09.1/amazon-corretto-8.232.09.1-macosx-x64.pkg > amazon-corretto-8.232.09.1-macosx-x64.pkg
      sudo installer -pkg amazon-corretto-8.232.09.1-macosx-x64.pkg -target /
      export OLD_JAVA_HOME=${JAVA_HOME}
      export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home
      rm amazon-corretto-8.232.09.1-macosx-x64.pkg
      ./platform_osx/build.sh
      ;;
    esac;
    javac -version;

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - export JAVA_HOME=${OLD_JAVA_HOME}
  - mvn sonar:sonar -Dsonar.projectKey=christiansantapaola_bookkeeper

